---
title: "Projects"
---
```{r  include=FALSE}
library(kableExtra)
library(dplyr)
library(knitr)
            
```

## Below is a list of projects proposed to use the SoDaH database:  

```{r echo = FALSE, results = 'asis'}
dt <- data.frame(
  Link    = rep(1,7,1),
  Project = c('Measurement recommendations for diverse practitioners' ,
              "SoDaH database paper",
              'Soil stoichiometric coupling & variability',
              'Big gradients and SOC controls', 
              'Linking root and soil carbon across sites',
              'Bulk Density & SOC', 
              'Detecting a signal from the noise: Power analysis and SOC variability'),
  Lead    = c('S. Billings & K. Lajtha',
              "W. Wieder", 
              'E. Kyker-Snowman',
              'K. Georgiou', 
              'A. Malhotra',
              'S. Grandy', 
              'D. Pierson'),
  Status  = c('_Ecological Applications_, 2020. [doi:10.1002/eap.2290](https://esajournals.onlinelibrary.wiley.com/doi/10.1002/eap.2290)', 
              "_Earth System Science Data_, 2021. [doi:10.5194/essd-13-1843-2021](https://essd.copernicus.org/articles/13/1843/2021/essd-13-1843-2021.pdf)", 
              'In progress, 2020 ESA talk',
              '_Biogeochemistry_, 2021. [doi:10.1007/s10533-021-00819-2](https://link.springer.com/article/10.1007/s10533-021-00819-2).', 
              'In progress, 2020 ESA talk',
              'S. Weintraub is exploring PTFs w/ NEON data', 
              'In progress, how do we capture heterogeneity with nested design?'
              )
)
dt_link <- c("https://docs.google.com/presentation/d/1R4osnHwq8MGth2F2OKbfX4OsG7G2jvYw7oq8JSPDXJc/edit?usp=sharing",
             "",
             "https://docs.google.com/presentation/d/1E_PXtafZNPuxd3vUdz4fBon1JKY7uyhgHquqwyDAMdQ/edit?usp=sharing",
             "https://docs.google.com/presentation/d/1BlWMDi3KD6x3wcg1LtHeMIde6IkR5QsornIPU6mhyFo/edit?usp=sharing",
             "https://docs.google.com/presentation/d/1HdctHoEX6Nh8KvgkS4uS6Ss6I3sa0izC9-nXgt_l_Oo/edit?usp=sharing",
             "https://docs.google.com/presentation/d/1JBcKzG1TRpEAu3tPIfjqy7jvJIOusw0paH4FtfBP0lA/edit?usp=sharing",
             "https://docs.google.com/document/d/1JdfkX7YkpLt-G-lPxe7N-FZ9rsNybKPbhmpfb-mxAcc/edit?usp=sharing")

dt %>% 
  mutate(Link = cell_spec(row.names(.), "html", link = dt_link)) %>%
  kable("html", escape = FALSE) %>%
  kable_styling(bootstrap_options = c("hover", "condensed")) 

            
#kable(dt)
```

## Want to join an existing project?
#### Contact the lead identified above and pitch in!  

## Have an idea for a new project?  
#### [Copy this slide](https://docs.google.com/presentation/d/1ozAdynewJ8lZcKTELxbXJPBeId1jKp9QsBk7WXIOu-Y/edit?usp=sharing) and send a copy to wwieder(at)ucar.edu!